build-job:
  tags:
    - macos
  stage: build
  script:
    - npm install
    - eas build --local \
      --non-interactive \
      --output ./build \
      --platform ios \
      --profile development