module.exports = {
    preset: 'react-native',
    testEnvironment: 'node',
    setupFiles: ["<rootDir>/jest.setup.js"],
    transform: {
        '^.+\\.(ts|tsx)?$': 'ts-jest',
        '^.+\\.(js|jsx)$': 'babel-jest',
        '\\.(png|jpg|jpeg|gif|svg)$': 'jest-transform-stub',
    },
    transformIgnorePatterns: [
        'node_modules/(?!(jest-)?react-native|@react-navigation|@react-native-firebase|@react-native|react-native|expo-calendar|expo-modules-core|expo-status-bar|expo-application|react-native-reanimated|@expo/vector-icons)',
    ],
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node', 'ios.js', 'android.js'],
    moduleNameMapper: {
        '^react-native$': 'react-native',
        '^react-native/(.*)': 'react-native/$1',
        '^@react-native-firebase/messaging$': '<rootDir>/tests/__mocks__/messaging.js',
        '^react-native-gesture-handler$': '<rootDir>/tests/__mocks__/react-native-gesture-handler.js',
        '^expo-modules-core$': '<rootDir>/tests/__mocks__/expo-modules-core.js',
        '^react-native-reanimated$': '<rootDir>/__mocks__/react-native-reanimated.js',
        '@components/(.*)': '<rootDir>/src/components/$1',
        '@themes/(.*)': '<rootDir>/src/styles/themes/$1',
        '@assets/(.*)': '<rootDir>/public/assets/$1',
        '@text/(.*)': '<rootDir>/public/text/$1',
        '@screens/(.*)': '<rootDir>/src/screens/$1',
        '@utils/(.*)': '<rootDir>/src/utils/$1',
        '@type/(.*)': '<rootDir>/src/types/$1',
        '@shared/(.*)': '<rootDir>/src/shared/$1',
        '@styles/(.*)': '<rootDir>/src/styles/$1',
        '@interfaces': '<rootDir>/interfaces.ts',
        '@redux/(.*)': '<rootDir>/src/redux/$1',
        '@nav/(.*)': '<rootDir>/src/components/nav/$1',
        '@constants': '<rootDir>/constants.ts',
        '@/(.*)': '<rootDir>/src/$1',
        '^@/(.*)$': '<rootDir>/$1',
    },
    testPathIgnorePatterns: ['/node_modules/', '/__mocks__/'],
}
